add blacklist function
deeper-chain/deeper-chain pull request #334
Opened 2022-10-02 17:34 UTC by geb789

What does this PR do?

1. Add an account into black list;
2. Delete an account from black list;
3. Check  whether an account is on the blacklist;

This PR has been tested by:

Unit Tests
Manual Testing
Follow up

Extra details

2022-10-04 09:04 UTC, jerry-yu commented on pallets/staking/src/lib.rs
> +            ensure_root(origin)?;
Here maybe use privilege user is better. see  pallet_user_privelleges

2022-10-04 09:09 UTC, jerry-yu commented
For passing CI，should run cargo fmt --all

2022-10-04 09:11 UTC, jerry-yu commented on pallets/staking/src/weights.rs
> +    fn add_account_to_blacklist() -> Weight;
The funciton of weight.rs  is auto created by benchmarking.rs .  see benchmarking.rs  for details

2022-10-06 07:39 UTC, jerry-yu approved these changes

2022-10-06 07:47 UTC, jerry-yu reviewed
The blacklist not exactly freeze   paying reward. 
see line 2707, T::Currency::deposit_creating, that acturally func for mint balance for user be

2022-10-06 07:49 UTC, jerry-yu requested changes
should judge before T::Currency::deposit_creating L2707

2022-10-06 12:39 UTC, geb789 commented
@jerry-yu thanks for your comment.

2022-10-08 02:36 UTC, jerry-yu approved these changes

2022-10-08 02:38 UTC, merged